FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# Establecer variable de entorno para ignorar errores de lint
ENV NEXT_IGNORE_ESLINT=1

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]